In [1]:
import pandas as pd
import numpy as np
from pandas import Timedelta
from datetime import timedelta
from sklearn.datasets import load_wine
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
df = pd.read_pickle("../seatunnel.pkl")
df = df.drop_duplicates()

In [3]:
df

begin_sha  \
0     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
1     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
2     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
3     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
4     bde19b6377f7b2fb7a34b94bd06d6ce0cc44f348   
...                                        ...   
5215  04addef64bbd2567d47acbb7f434245fba7ac8a5   
5216  79339df3455c88ba606847d79b3b3a1682c97a67   
5217  a475a8082b030af51a03e61457ed78b7cf17ab56   
5218  96d0637c8471ec9370f15a522db0b23ff5dc7669   
5219  b35ec02811bf7ef58bc8d831418c468ecc0a36b6   

                                       end_sha  commits  additions  deletions  \
0     4d429cab55482986b4d8a24c699d315631c8242a        1         64          1   
1     4d429cab55482986b4d8a24c699d315631c8242a        1         64          1   
2     c30a2a1b1c989d71082e7d501752f0d2d2c3601f        2         11         19   
3     c30a2a1b1c989d71082e7d501752f0d2d2c3601f        2         11         19   
4     c7745e63373c0fc92884982844bf55e22dd38af5        1          6          2   
...                                        ...      ...        ...        ...   
5215  3b6a8b4058593b1ff11c44560ebcc56142cda830        1         11       1128   
5216  04addef64bbd2567d47acbb7f434245fba7ac8a5        1         36          0   
5217  a26d21b7d28704facbfbbecfb501b958dd59d826        6        997       1045   
5218  5fa746466941d871d4b1246b451f398416952541       14        964        122   
5219  305ec511da05ba519fe4b04b46f7898b650b06c5        1         97         28   

      changed_files       total_time            begin_time  \
0                 1  0 days 00:33:23  2023-06-06T08:28:39Z   
1                 1  0 days 00:33:23  2023-06-02T07:23:42Z   
2                 3  4 days 01:37:00  2023-06-06T08:28:39Z   
3                 3  4 days 01:37:00  2023-06-02T07:23:42Z   
4                 1  0 days 17:17:51  2023-06-05T08:59:42Z   
...             ...              ...                   ...   
5215             27  0 days 00:33:35  2019-08-13T15:14:02Z   
5216              1  0 days 00:09:14  2019-08-13T02:16:57Z   
5217             81  0 days 23:14:31  2019-08-13T01:54:31Z   
5218             64 31 days 01:05:35  2019-08-10T13:15:19Z   
5219             56  0 days 17:01:00  2019-07-19T10:36:13Z   

                                              begin_key  \
0     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
1     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
2     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
3     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
4     seatunnel-bde19b6377f7b2fb7a34b94bd06d6ce0cc44...   
...                                                 ...   
5215  seatunnel-04addef64bbd2567d47acbb7f434245fba7a...   
5216  seatunnel-79339df3455c88ba606847d79b3b3a1682c9...   
5217  seatunnel-a475a8082b030af51a03e61457ed78b7cf17...   
5218  seatunnel-96d0637c8471ec9370f15a522db0b23ff5dc...   
5219  seatunnel-b35ec02811bf7ef58bc8d831418c468ecc0a...   

                                begin_revision  ...  end_java:S5411  \
0     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...              13   
1     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...              13   
2     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...              13   
3     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...              13   
4     bde19b6377f7b2fb7a34b94bd06d6ce0cc44f348  ...              13   
...                                        ...  ...             ...   
5215  04addef64bbd2567d47acbb7f434245fba7ac8a5  ...               0   
5216  79339df3455c88ba606847d79b3b3a1682c97a67  ...               0   
5217  a475a8082b030af51a03e61457ed78b7cf17ab56  ...               0   
5218  96d0637c8471ec9370f15a522db0b23ff5dc7669  ...               0   
5219  b35ec02811bf7ef58bc8d831418c468ecc0a36b6  ...               0   

      end_java:S5413  end_java:S5803  end_java:S5869  end_java:S5993  \
0                  0               1               2              42   
1           

In [4]:
# time_median= df['total_time'].median()
# time_median
# Timedelta('1 days 00:38:47')

In [5]:
df['total_time'][0:30].median()

Timedelta('3 days 01:27:48')

In [6]:
df['total_time'] = pd.to_datetime(df['end_time']) - pd.to_datetime(df['begin_time'])

In [7]:
df['total_time'] < timedelta(minutes=1)

0       False
1       False
2       False
3       False
4       False
        ...  
5215    False
5216    False
5217    False
5218    False
5219    False
Name: total_time, Length: 5208, dtype: bool

In [8]:
# time_median > timedelta(minutes=0)

In [9]:
df['time_binary'] = df['total_time'].apply(lambda x:  0 if x < timedelta (days = 3) else 1)

In [10]:
df

begin_sha  \
0     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
1     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
2     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
3     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142   
4     bde19b6377f7b2fb7a34b94bd06d6ce0cc44f348   
...                                        ...   
5215  04addef64bbd2567d47acbb7f434245fba7ac8a5   
5216  79339df3455c88ba606847d79b3b3a1682c97a67   
5217  a475a8082b030af51a03e61457ed78b7cf17ab56   
5218  96d0637c8471ec9370f15a522db0b23ff5dc7669   
5219  b35ec02811bf7ef58bc8d831418c468ecc0a36b6   

                                       end_sha  commits  additions  deletions  \
0     4d429cab55482986b4d8a24c699d315631c8242a        1         64          1   
1     4d429cab55482986b4d8a24c699d315631c8242a        1         64          1   
2     c30a2a1b1c989d71082e7d501752f0d2d2c3601f        2         11         19   
3     c30a2a1b1c989d71082e7d501752f0d2d2c3601f        2         11         19   
4     c7745e63373c0fc92884982844bf55e22dd38af5        1          6          2   
...                                        ...      ...        ...        ...   
5215  3b6a8b4058593b1ff11c44560ebcc56142cda830        1         11       1128   
5216  04addef64bbd2567d47acbb7f434245fba7ac8a5        1         36          0   
5217  a26d21b7d28704facbfbbecfb501b958dd59d826        6        997       1045   
5218  5fa746466941d871d4b1246b451f398416952541       14        964        122   
5219  305ec511da05ba519fe4b04b46f7898b650b06c5        1         97         28   

      changed_files       total_time            begin_time  \
0                 1  0 days 00:33:23  2023-06-06T08:28:39Z   
1                 1  4 days 01:38:20  2023-06-02T07:23:42Z   
2                 3  0 days 00:32:03  2023-06-06T08:28:39Z   
3                 3  4 days 01:37:00  2023-06-02T07:23:42Z   
4                 1  0 days 17:17:51  2023-06-05T08:59:42Z   
...             ...              ...                   ...   
5215             27  0 days 00:33:35  2019-08-13T15:14:02Z   
5216              1  0 days 00:09:14  2019-08-13T02:16:57Z   
5217             81  0 days 23:14:31  2019-08-13T01:54:31Z   
5218             64 31 days 01:05:35  2019-08-10T13:15:19Z   
5219             56  0 days 17:01:00  2019-07-19T10:36:13Z   

                                              begin_key  \
0     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
1     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
2     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
3     seatunnel-c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1f...   
4     seatunnel-bde19b6377f7b2fb7a34b94bd06d6ce0cc44...   
...                                                 ...   
5215  seatunnel-04addef64bbd2567d47acbb7f434245fba7a...   
5216  seatunnel-79339df3455c88ba606847d79b3b3a1682c9...   
5217  seatunnel-a475a8082b030af51a03e61457ed78b7cf17...   
5218  seatunnel-96d0637c8471ec9370f15a522db0b23ff5dc...   
5219  seatunnel-b35ec02811bf7ef58bc8d831418c468ecc0a...   

                                begin_revision  ...  end_java:S5413  \
0     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...               0   
1     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...               0   
2     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...               0   
3     c203ef5f8d6ad8bfb7f284e32a9ce5f2bc1fe142  ...               0   
4     bde19b6377f7b2fb7a34b94bd06d6ce0cc44f348  ...               0   
...                                        ...  ...             ...   
5215  04addef64bbd2567d47acbb7f434245fba7ac8a5  ...               0   
5216  79339df3455c88ba606847d79b3b3a1682c97a67  ...               0   
5217  a475a8082b030af51a03e61457ed78b7cf17ab56  ...               0   
5218  96d0637c8471ec9370f15a522db0b23ff5dc7669  ...               0   
5219  b35ec02811bf7ef58bc8d831418c468ecc0a36b6  ...               0   

      end_java:S5803  end_java:S5869  end_java:S5993  end_java:S6202  \
0                  1               2              42               0   
1           

In [11]:
X = df.loc[:, ~df.columns.isin(['time_binary', 'total_time' ,'begin_sha', 'end_sha', 'begin_time' , 'begin_key', 'begin_revision', 'end_time', 'end_key', 'end_revision'])]
y = df['time_binary']

In [12]:
X

commits  additions  deletions  changed_files  begin_java:S100  \
0           1         64          1              1                0   
1           1         64          1              1                0   
2           2         11         19              3                0   
3           2         11         19              3                0   
4           1          6          2              1                0   
...       ...        ...        ...            ...              ...   
5215        1         11       1128             27                0   
5216        1         36          0              1                0   
5217        6        997       1045             81                0   
5218       14        964        122             64                0   
5219        1         97         28             56                0   

      begin_java:S101  begin_java:S106  begin_java:S1066  begin_java:S1068  \
0                   0                8                16                64   
1                   0                8                16                64   
2                   0                8                16                64   
3                   0                8                16                64   
4                   0                8                16                64   
...               ...              ...               ...               ...   
5215                0                0                 0                 2   
5216                0                0                 0                 2   
5217                0                0                 0                 0   
5218                0                1                 0                 0   
5219                0                0                 0                 0   

      begin_java:S107  ...  end_java:S5411  end_java:S5413  end_java:S5803  \
0                  27  ...              13               0               1   
1                  27  ...              13               0               1   
2                  27  ...              13               0               1   
3                  27  ...              13               0               1   
4                  27  ...              13               0               1   
...               ...  ...             ...             ...             ...   
5215                0  ...               0               0               0   
5216                0  ...               0               0               0   
5217                0  ...               0               0               0   
5218                0  ...               0               0               0   
5219                0  ...               0               0               0   

      end_java:S5869  end_java:S5993  end_java:S6202  end_java:S6213  \
0                  2              42               0             106   
1                  2              42               0             106   
2                  2              42               0             106   
3                  2              42               0             106   
4                  2              42               0             106   
...              ...             ...             ...             ...   
5215               0               0               0               0   
5216               0               0               0               0   
5217               0               0               0               0   
5218               0               0               0               3   
5219               0               0               0               1   

      end_java:S6244  end_java:S6353  end_java:S6355  
0                  1               0               0  
1                  1               0               0  
2                  1               0               0  
3                  1               0               0  
4                  1               0               0  
...              ...             ...             ...  
5215               0         

In [13]:
y

0       0
1       1
2       0
3       1
4       0
       ..
5215    0
5216    0
5217    0
5218    1
5219    0
Name: time_binary, Length: 5208, dtype: int64

In [14]:
X_train, X_test = X[:30], X[30:]
y_train, y_test = y[:30], y[30:]

In [31]:
X_train

commits  additions  deletions  changed_files  begin_java:S100  \
0         1         64          1              1                0   
1         1         64          1              1                0   
2         2         11         19              3                0   
3         2         11         19              3                0   
4         1          6          2              1                0   
5         1          7          7              1                0   
6         1          7          7              1                0   
7         1          7          7              1                0   
8         1          3          2              1                0   
9         1          3          2              1                0   
10        1          3          2              1                0   
11        1          1          0              1                0   
12        1          1          0              1                0   
13        1          1          0              1                0   
14        1         10          4              3                0   
15        1         10          4              3                0   
16        1         10          4              3                0   
17        1         10          4              3                0   
18        1         10          4              3                0   
19        1         10          4              3                0   
20        1          2          1              1                0   
21        1          2          1              1                0   
22        1          2          1              1                0   
23        1          2          1              1                0   
24        1          2          1              1                0   
25        1          2          1              1                0   
26        1         36         67              9                0   
27        1         36         67              9                0   
28        1         36         67              9                0   
29        1         36         67              9                0   

    begin_java:S101  begin_java:S106  begin_java:S1066  begin_java:S1068  \
0                 0                8                16                64   
1                 0                8                16                64   
2                 0                8                16                64   
3                 0                8                16                64   
4                 0                8                16                64   
5                 0                8                16                64   
6                 0                8                16                64   
7                 0                8                16                64   
8                 0                8                16                64   
9                 0                8                16                64   
10                0                8                16                64   
11                0                8                16                64   
12                0                8                16                64   
13                0                8                16                64   
14                0                8                16                64   
15                0                8                16                64   
16                0                8                16                64   
17                0                8                16                64   
18                0                8                16                64   
19                0                8                16                64   
20                0                8                16                64   
21                0                8                16                64   
22                0                8                16                64   
23                0                8    

In [15]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto' , random_state = 2))

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.29174664, 0.11900192, 0.0547025 , 0.27089337, 0.7079731 ])

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [18]:
confusion_matrix(y,y_pred)

array([[1160, 2526],
       [1178,  344]], dtype=int64)

In [19]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.11986062717770035
recall_score =  0.22601839684625494
f1_score 0.15664845173041891


In [20]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         1522
y_pred    2870
dtype: int64

In [21]:
from sklearn.model_selection import GridSearchCV

parameters = {

    'C': [0.01 , 0.1 ,1],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]

}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'gamma': ['scale', 'auto'],
                         'random_state': [2]},
             scoring='f1_macro')

In [22]:
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
clf.best_estimator_

SVC(C=1, random_state=2)

In [24]:
y_pred = clf.predict(X)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
y_pred_clf = clf.best_estimator_.predict(X)
y_pred_clf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ))
print('recall_score = ', recall_score(y,y_pred_clf ))
print('f1_score',f1_score(y,y_pred_clf ))

precision =  0.6115702479338843
recall_score =  0.04862023653088042
f1_score 0.09007912355447352


In [28]:
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
from matplotlib import pyplot as plt
from sklearn import svm
import numpy as np

def f_importances(coef, names):

    names = np.arange(1)
    imp = coef
    imp,names = zip(*sorted(zip(imp,names)))
    plt.barh(range(len(names)), imp, align='center')
    plt.yticks(range(len(names)), names)
    plt.show()

features_names = X.columns
svm1 = svm.SVC(kernel='linear',C=1)
svm1.fit(X, y)

SVC(C=1, kernel='linear')

In [30]:
svm1.coef_

array([[ 4.94582183e-02, -6.01160136e-04, -1.00632329e-03,
         5.01354307e-04,  4.43481348e-01,  1.77392539e-01,
         5.84774469e-02, -3.71104162e-01,  1.08907191e-01,
        -3.12704166e-01,  1.06544058e+00, -1.54267502e+00,
        -3.79745999e-01,  8.91096184e-02, -3.43149439e-01,
         1.82688137e+00, -6.80957134e-02,  2.35237677e-02,
        -1.26496718e-01,  4.25620234e-02, -1.31507900e-01,
        -2.02999682e-03, -2.63503748e-02, -3.16147257e-01,
         1.49729824e-01,  4.58099795e-01,  2.01652549e-01,
        -2.86892165e-01, -1.83113454e-01,  1.43683429e-01,
        -1.51563383e+00, -2.30944782e-01, -6.80023560e-01,
        -6.35248386e-01, -4.21032887e-01, -1.13387044e+00,
        -1.50250633e+00,  2.44999554e-01,  2.45399366e-01,
        -1.31456493e+00,  5.97616263e-01,  1.24090136e+00,
         1.23671421e-01,  4.93644078e-01, -2.51096177e-01,
        -5.73158170e-02,  1.02090649e+00, -8.08470063e-02,
         6.89114547e-02, -2.16388290e-01,  3.48424571e-0